Setup Typescript
ySnoopyDogy/MenheraBot pull request #34
Opened 2021-05-21 15:44 UTC by Tsugami

[x] - install and setup Typescript
[ ] - setup development and production mode

2021-05-21 18:40 UTC, Tsugami commented
conversion will use babel

2021-05-23 04:59 UTC, ySnoopyDogy commented on package.json
> +    "dev": "ts-node-dev -r tsconfig-paths/register --respawn --transpile-only --ignore-watch node_modules --no-notify src/index.ts",
Olá Yslan!!! Obrigada pelo seu PR! Gostarias de saber, antes de aprovar tais mudanças, se vossa senhoria tivesse a bela atitude de alterar o script 'dev' para adicionar a NODE_ENV 'development' assim como no 'start' pra production, obrigada!

2021-05-23 05:00 UTC, ySnoopyDogy commented on shard.js
> +const config = require('./config.json');
Pergunta rápida, pq aqui n pode ser tipo { token } = require(config)

2021-05-23 05:01 UTC, ySnoopyDogy requested changes
- Adicionar /dist na eslintignore
- Adicionar a node_env na development
- Dar um m!mamar @ySnoopyDogy no server de suporte

2021-05-23 05:02 UTC, Tsugami commented on shard.js
> +const config = require('./config.json');
no caso dos arquivos js não há problema, mas nos arquivos typescript gera um erro em modo de desenvolvimento.

2021-05-23 05:33 UTC, ySnoopyDogy approved these changes

2021-05-23 05:33 UTC, merged